src/appointments/urls.py
from django.conf.urls import url

from appointments.views import (
    AppointmentTemplate, AppointmentCreateDelete, AppointmentStatus
)

urlpatterns = [
    url(r'^create/(?P<slug>[-\w]+)/$', AppointmentTemplate.as_view(), name='create'),
    url(r'^edit/(?P<appointment_id>\d+)/$', AppointmentStatus.as_view(), name='status'),
    url(r'^(?P<slug>[-\w]+)/$', AppointmentCreateDelete.as_view(), name='base'),
]

src/dashboard/urls.py
from django.conf.urls import (url, include)
from django.contrib import admin

from dashboard.views import (
    DashboardHome, InstitutionList, 
    ServiceView, ServiceDeleteView,
    ProductView, ProductDeleteView
)

urlpatterns = [
    url(r'^$', DashboardHome.as_view(), name='home'),
    url(r'^search/', InstitutionList.as_view(), name='institution-list'),
    
    url(r'^services/delete', ServiceDeleteView.as_view(), name='services-delete'),
    url(r'^services/', ServiceView.as_view(), name='services'),

    url(r'^products/delete', ProductDeleteView.as_view(), name='products-delete'),
    url(r'^products/', ProductView.as_view(), name='products')
]

src/medcentermanager/urls.py
from django.conf.urls import (url, include)
from django.contrib import admin

from users.views import (RegistrationView, LoginView, LogoutView)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^appointments/', include('appointments.urls', namespace='appointments')),
    
    url(r'^registration/(?P<user_type>\w+)', RegistrationView.as_view(), name='registration'),
    url(r'^login/', LoginView.as_view(), name='login'),
    url(r'^logout/', LogoutView.as_view(), name='logout')
]

src/users/urls.py
from django.conf.urls import (url, include)

from users.views import (
    UserDetailView, UserUpdateView, FeedbackView
)


urlpatterns = [
    url(r'^edit/$', UserUpdateView.as_view(), name='update'),
    url(r'^(?P<slug>[-\w]+)/feedback/$', FeedbackView.as_view(), name='feedback'),
    url(r'^(?P<slug>[-\w]+)/$', UserDetailView.as_view(), name='detail')
]

src/dashboard/models.py
from django.db import models


class Service(models.Model):

    name = models.CharField(max_length=255, primary_key=True)
    # description = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Product(models.Model):
    
    product_id = models.AutoField(primary_key=True)
    generic_name = models.CharField(max_length=255, null=False)
    brand_name = models.CharField(max_length=255, null=False)
    manufacturer = models.CharField(max_length=255, null=True)

    def __str__(self):
        return self.generic_name

src/dashboard/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic import (View, ListView, DetailView)
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.shortcuts import (get_object_or_404, redirect)
from django.urls import reverse

User = get_user_model()

from users.models import (
    AdministratorDetails, AdministratorServices, AdministratorProducts, 
)
from dashboard.models import (Service, Product)
from appointments.models import Appointment


class DashboardHome(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard/home.html'

    def get_context_data(self, *args, **kwargs):
        context = super(DashboardHome, self).get_context_data(**kwargs)
        context['current_user'] = self.request.user
        context['services'] = Service.objects.all()
        context['products'] = Product.objects.all()
        context['my_services'] = AdministratorServices.objects.filter(admin__user=self.request.user)
        context['my_products'] = AdministratorProducts.objects.filter(admin__user=self.request.user)

        if self.request.user.is_admin:
            context['appointments'] = Appointment.objects.filter(admin__user=self.request.user, status='Accepted')
            context['pending_appointments'] = Appointment.objects.filter(admin__user=self.request.user, status='Pending')
        else:
            context['appointments'] = Appointment.objects.filter(user=self.request.user, status='Accepted')
            context['pending_appointments'] = Appointment.objects.filter(user=self.request.user, status='Pending')

        return context


class InstitutionList(LoginRequiredMixin, ListView):
    model = User 
    template_name = 'dashboard/institution_search.html'

    def get_context_data(self, *args, **kwargs):
        context = super(InstitutionList, self).get_context_data(**kwargs)

        institutions = User.objects.filter(is_admin=True)

        category = self.request.GET.get('c') or ' '
        location = self.request.GET.get('l') or ' '
        service = self.request.GET.get('s') or ' '
        product = self.request.GET.get('p') or ' '

        if category  != ' ':
            institutions = institutions.filter(administratordetails__category=category)
        
        if location  != ' ':
            institutions = institutions.filter(administratordetails__location__icontains=location)

        if service  != ' ':
            institutions = institutions.filter(administratordetails__administratorservices__service=service)

        if product  != ' ':
            generic_name, brand_name = product.split(' - ')
            institutions = institutions.filter(administratordetails__administratorproducts__product__generic_name__icontains=generic_name)

        context['institutions'] = institutions
        context['services'] = Service.objects.all()
        context['products'] = Product.objects.all()
        context['category'] = category
        context['location'] = location
        context['service'] = service
        context['product'] = product
        
        return context

    
class ServiceView(LoginRequiredMixin, View):
    template_name = 'dashboard/admin_services.html'

    def get_object(self):
        return self.request.user

    def get(self, request, *args, **kwargs):
        s_query = request.GET.get('s')

        services = Service.objects.all()
        my_services =  AdministratorServices.objects.filter(admin__user=self.request.user)
        my_services_names = [ inst.service.name for inst in my_services ]
        other_services = Service.objects.exclude(name__in=my_services_names)
        
        context = {
            'user': self.request.user,
            'services': services,
            'my_services': my_services,
            'other_services': other_services
        }

        if s_query:
            current_service = Service.objects.get(name=s_query)
            edit_service = AdministratorServices.objects.get(admin__user=self.request.user, service=current_service)
            context['edit_service'] = edit_service

        return render(request, self.template_name, context)
    
    def post(self, request, *args, **kwargs):
        name = request.POST.get('name')
        description = request.POST.get('description') or None
        price = request.POST.get('price')

        self_admin_instance = get_object_or_404(AdministratorDetails, user=self.request.user)
        service = None

        try:
            service = Service.objects.get(name=name)
        except Service.DoesNotExist:
            messages.error(request, 'Service does not exist'.format(name))
            return redirect(reverse('dashboard:services'))

        try:
            admin_service = AdministratorServices.objects.get(admin__user=self.request.user, service=service)

            """ If service with given admin and service exist, update current values"""
            admin_service.description = description
            admin_service.price = price
            admin_service.save()
            messages.success(request, 'Updated {} as a service. '.format(name))
        except AdministratorServices.DoesNotExist:
            """ If service with given admin does not exist, create a new AdministratorService """

            AdministratorServices.objects.create(
                admin=self_admin_instance,
                service=service,
                description=description,
                price=price
            )
            
            messages.success(request, 'Successfully added {} as a service'.format(name))

        return redirect(reverse('dashboard:services'))


class ServiceDeleteView(LoginRequiredMixin, View):

    def get_object(self):
        return self.request.user

    def get(self, request, *args, **kwargs):
        service = request.GET.get('s')
        AdministratorServices.objects.get(admin__user=self.request.user, service=service).delete()
        messages.success(request, '{} service deleted'.format(service))

        return redirect(reverse('dashboard:services'))


class ProductView(LoginRequiredMixin, View):
    template_name = 'dashboard/admin_products.html'

    def get_object(self):
        return self.request.user

    def get(self, request, *args, **kwargs):
        product_id = request.GET.get('p')
        
        products = Product.objects.all()
        my_products = AdministratorProducts.objects.filter(admin__user=self.request.user)
        my_product_ids = [ inst.product.product_id for inst in my_products ]
        other_products = Product.objects.exclude(product_id__in=my_product_ids)
        
        context = {
            'user': self.request.user,
            'products': products,
            'my_products': my_products,
            'other_products': other_products
        }

        if product_id:
            current_product = Product.objects.get(product_id=product_id)
            context['edit_product'] = AdministratorProducts.objects.get(admin__user=self.request.user, product=current_product)

        return render(request, self.template_name, context)
    
    def post(self, request, *args, **kwargs):
        product_id = request.POST.get('product_id')
        price = request.POST.get('price')
        stock = request.POST.get('stock')
        description = request.POST.get('description')

        self_admin_instance = get_object_or_404(AdministratorDetails, user=self.request.user)
        product = None

        try:
            product = Product.objects.get(product_id=product_id)
        except Product.DoesNotExist:
            messages.error(request, 'Product does not exist')
            return redirect(reverse('dashboard:products'))

        try:
            admin_product = AdministratorProducts.objects.get(admin=self_admin_instance, product=product)

            """ If Product with given admin and Product exist, update current values"""

            admin_product.price = price
            admin_product.stock = stock
            admin_product.description = description
            admin_product.save()
            messages.success(request, 'Successfully updated product')
        except AdministratorProducts.DoesNotExist:
            """ If Product with given admin does not exist, create a new AdministratorProduct """

            AdministratorProducts.objects.create(
                admin=self_admin_instance,
                product=product,
                price=price,
                stock=stock,
                description=description
            )
            messages.success(request, 'Successfully added {} - {} as a product'.format(product.generic_name, product.brand_name))

        return redirect(reverse('dashboard:products'))


class ProductDeleteView(LoginRequiredMixin, View):

    def get_object(self):
        return self.request.user

    def get(self, request, *args, **kwargs):
        product_id = request.GET.get('p')
        product = Product.objects.get(product_id=product_id)
        AdministratorProducts.objects.get(admin__user=self.request.user, product=product).delete()
        messages.success(request, '{} - {} product deleted'.format(product.generic_name, product.brand_name))

        return redirect(reverse('dashboard:products'))

src/templates/dashboard/admin_products.html
<div class="ui grid container center aligned" style="margin-top: 20px">
    <div class="eleven wide column">
        {% extends "base.html" %}
        
        {% block content %}
        <div class="ui secondary menu" style="border-top: 2px solid rgba(34, 36, 38, 0.15); padding:3px;">
            <a class="item" href={% url 'dashboard:home' %}>Home</a>
            <a class="item" href={% url 'dashboard:institution-list' %}>View institutions</a>
            <a class="item" href={% url 'users:update' %}>Edit My Profile</a>

            <div class="right secondary menu">
                <a class="ui item" href={% url 'logout' %}> <i class="sign out icon"></i> Logout</a>
            </div>

        </div>
    </div>
    <div class="fourteen wide column" style="padding-top:0px;">
        <div class="ui segment">
            <div class="ui two column aligned relaxed grid" style="margin-top:3px;">
                <div class="row">
                    <div class="column">
                        <h1 class="ui header">My Products</h1>
                        <div class="ui segment">
                            <div class="ui divided list modlist" style="text-align:left;">
                                {% for instance in my_products %}
                                <div class="item">
                                    <div class="right floated content">
                                        <div class="tiny ui buttons">
                                          <a href="{% url 'dashboard:products' %}?p={{ instance.product.product_id }}" class="tiny ui secondary button" style="padding:10px 13px;"><i class="write icon"></i> Edit</a>
                                          <a href="{% url 'dashboard:products-delete' %}?p={{ instance.product.product_id }}" class="tiny ui icon button" style><i class="trash icon"></i></a>
                                      </div>
                                  </div>
                                  <div class="content">
                                    <h4 class="header">{{ instance.product.brand_name }}</h4>
                                    <div>Generic name: {{ instance.product.generic_name }}</div>
                                    <div>Manufacturer: <strong>{{ instance.product.manufacturer }}</strong></div>
                                    <div>Price: {{ instance.price }}&nbsp;&nbsp;|&nbsp;&nbsp;Stock: {{ instance.stock}}</div>
                                    {{ instance.description}}<br>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="ui vertical divider" style="left:50%;"> </div>

                <div class="column" style="padding:0 30px;">
                    <h1 class="ui header">Add or Update a Product</h1>
                    <form class="ui form" action="{% url 'dashboard:products' %}" method="POST">
                        {% csrf_token %}

                        <div class="field">
                            <label for="product" align="left">Product: </label>
                            <select class="ui dropdown" name="product_id" id="">
                                {% if edit_product %}
                                <option value="{{ edit_product.product.product_id }}">
                                    {{ edit_product.product.generic_name }} - {{ edit_product.product.brand_name }}
                                </option>
                                {% else %}
                                <option value="">Select product...</option>
                                {% endif%}
                                {% for product in other_products %}
                                    <option value="{{ product.product_id }}">{{ product.generic_name}} - {{ product.brand_name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="two fields">
                            <div class="field"> 
                                <label for="price" align="left">Price:</label>
                                <input type="number" step="0.01" name="price" {% if edit_product %} value="{{ edit_product.price }}" {% endif %} required>
                            </div>

                            <div class="field">
                                <label for="stock" align="left">Stock:</label>
                                <input type="number" step="1" name="stock" {% if edit_product %} value="{{ edit_product.stock }}" {% endif %} required>
                            </div>
                        </div>

                        <div class="field">
                            <label for="description" align="left">Description:</label>
                            <textarea name="description"> {% if edit_product %} {{ edit_product.description }} {% endif %}</textarea>
                        </div>

                        <input type="submit" value="Submit" class="ui blue button" />
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</div>


<script type="text/javascript">
    $('.ui .dropdown').dropdown();
</script>
{% endblock %}

src/templates/dashboard/admin_services.html
<div class="ui grid container center aligned" style="margin-top: 20px">        
    <div class="eleven wide column">
            {% extends "base.html" %}
            
            {% block content %}
        <div class="ui secondary menu" style="border-top: 2px solid rgba(34, 36, 38, 0.15); padding:3px;">
            <a class="item" href={% url 'dashboard:home' %}>Home</a>
            <a class="item" href={% url 'dashboard:institution-list' %}>View institutions</a>
            <a class="item" href={% url 'users:update' %}>Edit My Profile</a>

            <div class="right secondary menu">
                <a class="ui item" href={% url 'logout' %}> <i class="sign out icon"></i> Logout</a>
            </div>

        </div>
    </div>
    <div class="fourteen wide column" style="padding-top:0px;">
        <div class="ui segment">
            <div class="ui two column aligned relaxed grid" style="margin-top:3px;">
                {% block messages %}{% endblock messages %}
                <div class="row">
                    <div class="column">
                        <h1 class="ui header">My Services</h1>
                        {% if my_services %}
                        <div class="ui segment">
                            <div class="ui divided list modlist" style="text-align:left;">
                                {% for instance in my_services %}
                                <div class="item">
                                    <div class="right floated content">
                                        <div class="tiny ui buttons">
                                          <a href="{% url 'dashboard:services' %}?s={{ instance.service.name }}" class="tiny ui secondary button" style="padding:10px 13px;"><i class="write icon"></i> Edit</a>
                                          <a href="{% url 'dashboard:services-delete' %}?s={{ instance.service.name }}" class="tiny ui icon button" style><i class="trash icon"></i></a>
                                      </div>
                                  </div>
                                  <div class="content">
                                    <h4 class="header">{{ instance.service.name }}</h4>
                                    <div>Price:&nbsp; {{ instance.price }} PHP</div>
                                    <div class="description" style="margin-top:3px;">{{ instance.description }}</div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>

                    {% else %}
                    <div>No services yet. Add one using the form in the right.</div>
                    {% endif %}
                </div>

                <div class="ui vertical divider" style="left:50%;"> </div>
                <div class="column" style="padding:0 30px;">
                    <h1 class="ui header">Add or Update a Service</h1>
                    <form class="ui form" action="{% url 'dashboard:services' %}" method="POST">
                        {% csrf_token %}
                        <div class="field">
                            <label for="Service" align="left">Service: </label>
                            <select class="ui dropdown" name="name">
                                {% if edit_service %} 
                                <option value="{{ edit_service.service.name }}">{{ edit_service.service.name }}</option>
                                {% else %}
                                <option value="">Select a service...</option>
                                {% endif %}
                                {% for service in other_services %}
                                <option value="{{ service.name }}">{{ service.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                         <div class="field">
                            <label for="price" align="left">Price:</label>
                            <input type="number" step="0.01" name="price" {% if edit_service %} value="{{ edit_service.price }}" {% endif %} required>
                        </div>
                        <div class="field">
                            <label for="description" align="left">Description:</label>
                            <textarea name="description"> {% if edit_service.description %} {{ edit_service.description }} {% endif %}</textarea>
                        </div>
                        <input type="submit" value="Submit" class="ui blue button"/>
                    </form>

                </div>

            </div>

            <div class="column" style="padding:0 30px;">


            </div>
        </div>
    </div>
</div>
</div></div>

<script type="text/javascript">
    $('.ui .dropdown').dropdown();
</script>

{% endblock %}

src/templates/dashboard/home.html
<div class="ui container centered grid">
	<div class="eleven wide column segment" >
		<div class="row">
			{% extends "base.html" %}

			{% block content %}
			<h1 class="ui header" align="left">Dashboard
				<div class="sub header" align="left" style="margin-bottom:5px;"><small>Welcome,&nbsp;
					<strong>{{ current_user.username }} </strong></small>
				</div></h1>
			</div>
			<div class="row">
				<div class="ui secondary menu" style="border-top: 2px solid rgba(34, 36, 38, 0.15); padding:3px;">
					<a class="active item" href={% url 'dashboard:home' %}>Home</a>
					<a class="item" href={% url 'dashboard:institution-list' %}>View institutions</a>
					<a class="item" href={% url 'users:update' %}>Edit My Profile</a>
					<a class="item" href={% url 'users:detail' slug=current_user.slug %}>View My Profile</a>

					<div class="right secondary menu">
						<a class="ui item" href={% url 'logout' %}> <i class="sign out icon"></i> Logout</a>
					</div>

				</div>
			</div>

			<div class="row">
				<div class="row" style="height:100%; margin-top:30px;">
					<div class="ui horizontal stacked segments grid" style="border-width: 0px;">
						<div class="eleven wide column" style="padding:0px;">
							<div class="ui segment" style="border-right-width:0px; border-bottom-width:0px; box-shadow:none; border-top-right-radius:0px;">
								<div style="padding:3px;">
									<div class="ui sidemenu active tab" data-tab="{% if current_user.is_admin == 0 %}scheduled-{% endif %}appointments">
										<h2>Scheduled Appointments</h2>
										{% if appointments %}
										<ul>
											{% for aptmt in appointments %}
											<li> 
												{% if current_user.is_admin %} 
													<span style="padding-right:15px;">{{ aptmt.date }} ({{ aptmt.timeslot }}): {{ aptmt.service }} for <a href="{% url 'users:detail' slug=aptmt.user.slug %}">{{ aptmt.user.username }}</a></span>
													<br>
														
													<span style="padding-right:15px;">Additional Info: {{ aptmt.additional_info }}</span>
												{% else %}
													<span style="padding-right:15px;">{{ aptmt.date }} ({{ aptmt.timeslot }}): {{ aptmt.service }} at <a href="{% url 'users:detail' slug=aptmt.admin.user.slug %}">{{ aptmt.admin.user.username }}</a></span>
												{% endif %}
												<a href="{% url 'appointments:status' appointment_id=aptmt.appointment_id %}?s=Cancelled"><button class="tiny ui orange button">Cancel</button></a>
												<a href="{% url 'appointments:status' appointment_id=aptmt.appointment_id %}?s=Done"><button class="tiny ui blue button">Done</button></a>
											</li>
											<br>
											{% endfor %}
										</ul>
										{% else %}
										<p>No scheduled appointments.</p>
										{% endif %}
										{% if current_user.is_admin == 0 %}</div><div class="ui sidemenu tab" data-tab="pending-appointments"> {% endif %}

										<h2>Pending Appointments</h2>
										{% if pending_appointments %}
										<ul>
											{% for aptmt in pending_appointments %}
											<li>
												{% if current_user.is_admin %} 
													<span>{{ aptmt.date }} ( {{ aptmt.timeslot }}): {{ aptmt.service }} for <a href="{% url 'users:detail' slug=aptmt.user.slug %}">{{ aptmt.user.username }}</a></span>
													<br>
													<a href="{% url 'appointments:status' appointment_id=aptmt.appointment_id %}?s=Accepted"><button class="tiny ui green button">Accept</button></a> 
													<a href="{% url 'appointments:status' appointment_id=aptmt.appointment_id %}?s=Rejected"><button class="tiny ui red button">Reject</button></a> 
												{% else %}
													<span style="padding-right:15px;">{{ aptmt.date }} ({{ aptmt.timeslot }}): {{ aptmt.service }} at <a href="{% url 'users:detail' slug=aptmt.admin.user.slug %}">{{ aptmt.admin.user.username }}</a></span>
													<a href="{% url 'appointments:status' appointment_id=aptmt.appointment_id %}?s=Cancelled"><button class="tiny ui orange button">Cancel</button></a>
												{% endif %}
											</li>
											<br>
											{% endfor %}
										</ul>

										{% else %}
										<p>No pending appointments.</p>
										{% endif %}
									</div>

									<div class="ui sidemenu tab" data-tab="services" style="position:relative;">
										<h1 class="ui header">Services Offered</h1>
										<a href="{% url 'dashboard:services' %}" class="small ui right primary button" style="position: absolute;top: 0;right:0;"><i class="edit icon"></i> Manage</a>
										<div class="row">
											<p></p>
											{% if my_services %}
											<div class="ui bulleted list">
												{% for instance in my_services %}
												<div class="item">
												{{ instance.service.name }} ({{ instance.price }} PHP)
													</div>
												{% endfor %}
											</div>
											{% else %}
											<p>No services yet.</p>

											{% endif %}
										</div>
									</div>

									<div class="ui sidemenu tab" data-tab="products" style="position:relative;">
										<h1 class="ui header">Products Offered</h1>
										<a href="{% url 'dashboard:products' %}" class="small ui right primary button" style="position: absolute;top: 0;right:0;"><i class="edit icon"></i> Manage</a>
										<div class="row">
											<p></p>
											{% if my_products %}
											<div class="ui bulleted list">
												{% for instance in my_products %}
												<div class="item">
													<div><h4 class="ui inline header">{{ instance.product.brand_name }}</h4>by {{ instance.product.manufacturer }}</div>
													<div>{{ instance.product.generic_name }}</div>
													<div>{{ instance.price }} PHP  /  {{ instance.stock }} in stock</div>
													<div>{{ instance.description }}</div>
												</div>
												{% endfor %}
											</div>
											{% else %}
											<p>No products yet.</p>
											{% endif %}
										</div>
									</div>
								</div>
							</div>
						</div>

						<!-- MENU -->
						<div class="fluid five wide column" style="padding:0px; display:flex;">
							<div class="fluid" style="display:flex; width: 100%;">
								<div class="ui fluid vertical right tabular menu" style="margin-bottom:3px;">
									<a class="sidemenu item active" data-tab="{% if current_user.is_admin == 0 %}scheduled-{% endif %}appointments">{% if current_user.is_admin == 0 %}Scheduled {% endif %}Appointments</a>
									{% if current_user.is_admin == 0 %}
									<a class="sidemenu item" data-tab="pending-appointments">Pending Appointments</a> 

									{% elif current_user.is_admin %}
									<a class="sidemenu item" data-tab="services">Services</a>
									<a class="sidemenu item" data-tab="products">Products</a>
									{% endif %}
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<script type="text/javascript">
	$('.sidemenu .item').on('click', function() {
		$('.sidemenu .item').removeClass('active');
		$(this).addClass('active');
	});             

	$('.menu .item').tab();
	$('.ui.dropdown').dropdown();
	</script>

	{% endblock %}

src/templates/dashboard/institution_search.html
<div class="ui grid container center aligned" style="margin-top: 20px">
	<div class="column"></div>
	<div class="eleven wide column"> 			

		{% extends "base.html" %}

		{% block content %}

		<div class="row">
			<div class="ui secondary menu" style="border-bottom: 2px solid rgba(34, 36, 38, 0.15);"	>
				<a class="item" href={% url 'dashboard:home' %}>Home</a>
				<a class="active item" href={% url 'dashboard:institution-list' %}>View institutions</a>
				<a class="item" href={% url 'users:update' %}>Edit My Profile</a>

				<div class="right secondary menu">
					<a class="ui item" href={% url 'logout' %}> <i class="sign out icon"></i> Logout</a>
				</div>
			</div>
		</div>

		<br><br>
		<div class="row">
			{% block search_bar %}
				{% include "dashboard/search_bar.html" %}
			{% endblock  %}
		</div>

		<table class="ui selectable celled table">
			<thead>
				<tr>
					<th>Institution</th>
					<th>Category</th>
					<th>Location</th>
					<th>Services</th>
					<th>Products</th>
					<th>Rating</th>
				</tr>
			</thead>
			<tbody>
				{% for inst in institutions%}
					<tr>
						<td><a href="{{ inst.get_profile }}">{{ inst.username | title }}</a></td>
						<td>{{ inst.administratordetails.category }}</td>
						<td>{{ inst.administratordetails.location }}</td>
						<td>
							{% for service in inst.administratordetails.services.all %}
								<li> {{ service }}</li>
							{% endfor %}
						</td>
						<td>
							{% for product in inst.administratordetails.products.all %}
								<li>{{ product.generic_name }} - {{ product.brand_name }}</li>
							{% endfor %}
						</td>
						<td>{{ inst.administratordetails.get_average_rating }}</td>
					</tr>
				</a>
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>
</div>
<br>
<br>
<br>

{% endblock %}