src/appointments/urls.py
from django.conf.urls import url

from appointments.views import (
    AppointmentTemplate, AppointmentCreateDelete, AppointmentStatus
)

urlpatterns = [
    url(r'^create/(?P<slug>[-\w]+)/$', AppointmentTemplate.as_view(), name='create'),
    url(r'^edit/(?P<appointment_id>\d+)/$', AppointmentStatus.as_view(), name='status'),
    url(r'^(?P<slug>[-\w]+)/$', AppointmentCreateDelete.as_view(), name='base'),
]

src/dashboard/urls.py
from django.conf.urls import (url, include)
from django.contrib import admin

from dashboard.views import (
    DashboardHome, InstitutionList, 
    ServiceView, ServiceDeleteView,
    ProductView, ProductDeleteView
)

urlpatterns = [
    url(r'^$', DashboardHome.as_view(), name='home'),
    url(r'^search/', InstitutionList.as_view(), name='institution-list'),
    
    url(r'^services/delete', ServiceDeleteView.as_view(), name='services-delete'),
    url(r'^services/', ServiceView.as_view(), name='services'),

    url(r'^products/delete', ProductDeleteView.as_view(), name='products-delete'),
    url(r'^products/', ProductView.as_view(), name='products')
]

src/medcentermanager/urls.py
from django.conf.urls import (url, include)
from django.contrib import admin

from users.views import (RegistrationView, LoginView, LogoutView)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^appointments/', include('appointments.urls', namespace='appointments')),
    
    url(r'^registration/(?P<user_type>\w+)', RegistrationView.as_view(), name='registration'),
    url(r'^login/', LoginView.as_view(), name='login'),
    url(r'^logout/', LogoutView.as_view(), name='logout')
]

src/users/urls.py
from django.conf.urls import (url, include)

from users.views import (
    UserDetailView, UserUpdateView, FeedbackView
)


urlpatterns = [
    url(r'^edit/$', UserUpdateView.as_view(), name='update'),
    url(r'^(?P<slug>[-\w]+)/feedback/$', FeedbackView.as_view(), name='feedback'),
    url(r'^(?P<slug>[-\w]+)/$', UserDetailView.as_view(), name='detail')
]

src/users/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser,
)

from dashboard.models import (
    Service, Product
)

INSTITUTION_CHOICES = ['treatment_center', 'social_hygiene_clinic', 'testing_hub']


class BaseUserManager(BaseUserManager):
    
    def create_user(self, username, email, mobile_number=None, landline_number=None, is_admin=False, password=None):
        """ 
        Creates and saves a RegularUser with given information and hashed password
        """

        if not email or not username:
            raise ValueError('Users must have an email address')

        if self.model.objects.filter(email=email).first():
            raise ValueError('Email address is already taken')

        if self.model.objects.filter(username=username).first():
            raise ValueError('Username is already taken')
        
        user = self.model(
            username=username,
            email=self.normalize_email(email),
            mobile_number=mobile_number,
            landline_number=landline_number,
            is_admin=is_admin,
            slug=slugify(username)
        )

        user.set_password(password)
        user.save(using=self._db)
        
        return user


class BaseUser(AbstractBaseUser):

    user_id = models.AutoField(primary_key=True)
    
    # Displayed as Institution Name for Administrators
    username = models.CharField(max_length=255, unique=True, null=False)
    
    email = models.EmailField(max_length=255, unique=True, null=False)
    mobile_number = models.CharField(max_length=40, unique=True, null=True)
    landline_number = models.CharField(max_length=40, unique=True, null=True)
    is_admin = models.BooleanField(default=False)
    slug = models.SlugField(unique=True)

    objects = BaseUserManager()
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.username

    def get_profile(self):
        return reverse('users:detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.email


class AdministratorDetailsManager(models.Manager):
    
    def create_administrator(self, username, email, mobile_number, landline_number, 
                            open_time, close_time, address, location, category, staff, additional_info,
                            password=None):
        
        if not email or not username:
            raise ValueError('Administrators must have an email address')

        user = BaseUser.objects.create_user(username, email, mobile_number, landline_number, True, password=password)
        print(user)

        administrator_details = self.model(
            user=user,
            open_time=open_time,
            close_time=close_time,
            address=address,
            location=location,
            category=category,
            staff=staff,
            additional_info=additional_info
        )

        print(administrator_details)

        administrator_details.save()
        print('done')

        return administrator_details


class AdministratorDetails(models.Model):
    """ AdministratorDetails model """    

    user = models.OneToOneField(BaseUser, on_delete=models.CASCADE, primary_key=True)
    open_time = models.CharField(max_length=5, null=True) # '08:00'
    close_time = models.CharField(max_length=5, null=True) # '18:00'
    address = models.TextField(null=False)
    location = models.CharField(max_length=255, null=True)
    category = models.CharField(max_length=21, null=False)
    staff = models.TextField(null=True)
    additional_info = models.TextField(null=True)

    services = models.ManyToManyField(Service, through='AdministratorServices')
    products = models.ManyToManyField(Product, through='AdministratorProducts')
    
    objects = AdministratorDetailsManager()

    def get_average_rating(self):
        try: 
            feedback = Feedback.objects.filter(admin=self.user.administratordetails)
            return round(sum([ fb.rating for fb in feedback ]) / feedback.count(), 2)
        except ZeroDivisionError:
            return 'Not yet rated'

    def __str__(self):
        return self.user.email


class AdministratorServices(models.Model):

    admin_service_id = models.AutoField(primary_key=True)
    admin = models.ForeignKey(AdministratorDetails)
    service = models.ForeignKey(Service)
    description = models.TextField(null=True)
    price = models.FloatField()

    def __str__(self):
        return '{}-{}'.format(self.admin, self.service)


class AdministratorProducts(models.Model):

    admin_product_id = models.AutoField(primary_key=True)
    admin = models.ForeignKey(AdministratorDetails)
    product = models.ForeignKey(Product)
    price = models.FloatField(null=True)
    stock = models.IntegerField(null=True)
    description = models.TextField(null=True)

    def __str__(self):
        return '{}-{}'.format(self.admin, self.product)


class Feedback(models.Model):
    
    feedback_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(BaseUser, on_delete=models.CASCADE)
    admin = models.ForeignKey(AdministratorDetails, on_delete=models.CASCADE)
    rating = models.IntegerField(null=False)
    comment = models.TextField()

    def __str__(self):
        return '{} to {} ({}): {}'.format(self.user, self.admin, self.rating, self.comment)

src/users/views.py
from django.shortcuts import (render, redirect)
from django.http import HttpResponseRedirect
from django.views.generic import (View, DetailView)
from django.views.generic.base import TemplateView
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import (get_user_model, authenticate, login, logout)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.utils.text import slugify
from django.core.exceptions import ObjectDoesNotExist

from dashboard.models import Service
from users.models import (
    Feedback, AdministratorDetails, AdministratorServices, AdministratorProducts
)
from appointments.models import (
    Timeslot, Appointment
)
from medcentermanager import settings

User = get_user_model()


class RegistrationView(View):
    def get(self, request, *args, **kwargs):
        template_name = 'auth/registration.html'
        user_type = kwargs.get('user_type')

        if user_type == 'administrator':
            template_name = 'auth/administrator_fields.html'

        context = {
            'user_type': user_type
        }
        
        return render(request, template_name, context)

    def post(self, request, *args, **kwargs):
        user_type = kwargs.get('user_type')
        new_instance = {}

        username = request.POST.get('username')
        email = request.POST.get('email')
        mobile_number = request.POST.get('mobile_number') or None
        landline_number = request.POST.get('landline_number') or None

        open_time = request.POST.get('open_time') or None
        close_time = request.POST.get('close_time') or None
        address = request.POST.get('address') or None
        location = request.POST.get('location') or None
        category = request.POST.get('category')
        staff = request.POST.get('staff') or None
        additional_info = request.POST.get('additional_info') or None

        password = request.POST.get('password')

        try:
            if user_type == 'regular':
                new_instance = User.objects.create_user(
                    username=username,
                    email=email,
                    mobile_number=mobile_number,
                    landline_number=landline_number,
                    password=password
                )    
            elif user_type == 'administrator':
                new_instance = AdministratorDetails.objects.create_administrator(
                    username=username,
                    email=email,
                    mobile_number=mobile_number,
                    landline_number=landline_number,
                    open_time=open_time,
                    close_time=close_time,
                    address=address,
                    location=location,
                    category=category, 
                    staff=staff,
                    additional_info=additional_info,
                    password=password
                )
            context = {
                'user_type': user_type,
                'new_user': new_instance
            }

            messages.success(request, 'Profile created. Please log in')
            
            return redirect(reverse('login'))
        except ValueError as e:
            messages.error(request, e)
            return redirect(reverse('registration', kwargs={'user_type': user_type}))
        except:
            messages.error(request, 'Sign up failed')
            return redirect(reverse('registration', kwargs={'user_type': user_type}))


class LoginView(TemplateView):
    template_name = 'auth/login.html'

    def post(self, request, *args, **kwargs):
        email = request.POST.get('email')
        password = request.POST.get('password')

        try:
            user = authenticate(request, username=email, password=password)
            
            if user is not None:
                login(request, user)
                return redirect(reverse('dashboard:home'))
        except:
            messages.error(request, 'Login failed')
            return self.get(request)


class LogoutView(View):
    """ Provides users the ability to logout """

    def get(self, request, *args, **kwargs):
        messages.success(request, 'You have successfully logged out')
        logout(request)
        return redirect(settings.LOGIN_URL)


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'users/user.html'

    def get_context_data(self, *args, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        slug = self.kwargs.get('slug')
        fid = self.request.GET.get('fid')
        user_viewed = User.objects.get(slug=slug)

        context['current_user'] = self.request.user
        context['feedback'] = Feedback.objects.filter(admin__user=user_viewed)
        context['my_appointments_here'] = Appointment.objects.filter(user=self.request.user, admin__user=user_viewed, status='Accepted')
        context['user_viewed_products'] = AdministratorProducts.objects.filter(admin__user=user_viewed)
        context['user_viewed_services'] = AdministratorServices.objects.filter(admin__user=user_viewed)

        if fid:
            context['current_feedback'] = Feedback.objects.get(feedback_id=fid)

        return context

class UserUpdateView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'users/user_update.html'

    def get_object(self):
        return self.request.user

    def post(self, request, *args, **kwargs):
        username = request.POST.get('username')
        email = request.POST.get('email')
        mobile_number = request.POST.get('mobile_number') or None
        landline_number = request.POST.get('landline_number') or None

        open_time = request.POST.get('open_time') or None
        close_time = request.POST.get('close_time') or None
        address = request.POST.get('address') or None
        location = request.POST.get('location') or None
        category = request.POST.get('category')
        staff = request.POST.get('staff') or None
        additional_info = request.POST.get('additional_info') or None

        password = request.POST.get('password')

        user = get_object_or_404(User, email=email)

        if user.check_password(password):
            print('password is good')
            try:
                user.username = username
                user.email = email
                user.mobile_number = mobile_number
                user.landline_number = landline_number
                user.slug = slugify(username)
                user.save()
            
                user.administratordetails.open_time = open_time
                user.administratordetails.close_time = close_time
                user.administratordetails.address = address
                user.administratordetails.location = location
                user.administratordetails.category = category
                user.administratordetails.staff = staff
                user.administratordetails.additional_info = additional_info
                user.administratordetails.save()
            except ObjectDoesNotExist:
                pass 
            except:
                messages.error(request, 'There was a problem in updating your profile')
            messages.success(request, 'Successfully updated profile')
        else:
            messages.error(request, 'There was a problem verifying your profile')

        return redirect(reverse('users:update'))


class FeedbackView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        fid = request.GET.get('fid')
        slug = kwargs.get('slug')
        feedback = Feedback.objects.get(feedback_id=fid)
        
        if feedback.user == self.request.user:
            feedback.delete()
            messages.success(request, 'Successfully deleted your comment')
        else:
            messages.error(request, 'Error in deleting your comment')
        
        return redirect(reverse('users:detail', kwargs={'slug': slug}))

    def post(self, request, *args, **kwargs):
        slug = kwargs.get('slug')
        fid = request.POST.get('feedback_id')
        rating = request.POST.get('rating')
        comment = request.POST.get('comment')
        admin = AdministratorDetails.objects.get(user__slug=slug)
        
        try: 
            if fid:
                current_feedback = Feedback.objects.get(feedback_id=fid)
                current_feedback.rating = rating
                current_feedback.comment = comment 
                current_feedback.save()
                messages.success(request, 'Successfully edited comment')
            else:
                Feedback.objects.create(
                    user=self.request.user,
                    admin=admin,
                    rating=rating,
                    comment=comment
                )
                messages.success(request, 'Successfully added comment')
        except:
            messages.error(request, 'An error occured with your comment')

        return redirect(reverse('users:detail', kwargs={'slug': slug}))

src/templates/users/baseuser_detail.html
{% extends "base.html" %}

{% block content %}
<div>
    <h1>Edit Profile</h1>
    <form action={% url 'users:detail' slug=object.slug %} method="PUT">
        {% csrf_token %}


        <label for="username">Username: </label>
        <input type="text" name="username" value={{ object.username }} />
        <br>
        <br>   

        <label for="email">Email: </label>
        <input type="text" name="email" value={{ object.email }} />
        <br>
        <br>
        
        <label for="mobile_number">Mobile Number: </label>
        <input type="text" name="mobile_number" value={{ object.mobile_number }} />
        <br>
        <br>
        
        <label for="landline_number">Landline Number: </label>
        <input type="text" name="landline_number" value={{ object.landline_number }} />
        <br>
        <br>
        
        <input type="submit" value="Edit" />
    </form>
</div>

{% endblock %}

src/templates/users/user.html
<div class="ui grid container centered aligned">
    <div class="column"></div>
    <div class="eleven wide column">  
        {% extends "base.html" %}

        {% block content %}
        
        <div class="row">
            <div class="ui secondary menu" style="border-bottom: 2px solid rgba(34, 36, 38, 0.15);" >
              <a class="item" href={% url 'dashboard:home' %}>Home</a>
              <a class="active item" href={% url 'dashboard:institution-list' %}>View institutions</a>
              <a class="item" href={% url 'users:update' %}>Edit My Profile</a>
              <a class="item" href={% url 'users:detail' slug=current_user.slug %}>View My Profile</a>

              <div class="right secondary menu">
                <a class="ui item" href={% url 'logout' %}> <i class="sign out icon"></i> Logout</a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="ui padded stacked segment" style="margin-top: 20px;">           
            <h1>{{ object.username }}</h1>

            <div class="ui top attached tabular sidemenu menu">
                <a class="sidemenu {% if not current_feedback %}active{% endif %} item" data-tab="profile">Profile</a>
                {% if object.is_admin %}
                <a class="sidemenu item" data-tab="services">Services Offered</a>
                <a class="sidemenu item" data-tab="products">Products</a>
                {% if not current_user.is_admin %}
                <a class="sidemenu item" data-tab="appointments">Appointments</a>
                {% endif %}
                <a class="sidemenu {% if current_feedback %}active{% endif %} item" data-tab="feedback">Feedback</a>
                {% endif %}
            </div>
            <div class="ui bottom attached segment">
              <div class="ui sidemenu {% if not current_feedback %}active{% endif %} tab" data-tab="profile">
                <div class="ui basic segment" style="text-align: left">
                    <div class="ui list">
                      <div class="item">
                        <i class="mail icon"></i>
                        <div class="content">{{ object.email }}</div>
                    </div>
                    {% if object.mobile_number %}
                    <div class="item">
                        <i class="mobile icon"></i>
                        <div class="content">{{ object.mobile_number }}</div>
                    </div>
                    {% endif %}

                    {% if object.landline_number %}
                    <div class="item">
                        <i class="call icon"></i>
                        <div class="content">{{ object.landline_number }}</div>
                    </div>
                    {% endif %}
                    {% if object.is_admin %}
                    <div class="item">
                        <div class="content"><i class="fa fa-clock-o"></i> &nbsp;&nbsp;&nbsp;{{ object.administratordetails.open_time }} - {{ object.administratordetails.close_time }}</div>
                    </div>
                    <div class="item">
                        <i class="marker icon"></i>
                        <div class="content">{{ object.administratordetails.location }}</div>
                    </div>
                    <div class="item">
                        <i class="emergency icon"></i>
                        <div class="content">{{ object.administratordetails.category }}</div>
                    </div>
                    <div class="item">
                        <i class="user icon"></i>
                        <div class="content">{{ object.administratordetails.staff }}</div>
                    </div>
                    <div class="item">
                        <i class="info circle icon"></i>
                        <div class="content">{{ object.administratordetails.additional_info }}</div>
                    </div>
                    {% endif %}
                </div>
            </div>

        </div>

        <div class="ui sidemenu tab" data-tab="services">
            <div class="ui basic segment">
                <h2>Services Offered</h2>
                <div class="ui divided list modlist" style="text-align:left;">
                    {% for instance in user_viewed_services %}
                    <div class="item">
                        <div class="content">
                            <h4 class="header">{{ instance.service }}</h4>
                            <div>Price:&nbsp; {{ instance.price }} PHP</div>
                            <div class="description" style="margin-top:3px;">{{ instance.description }}</div>
                        </div>

                    </div> 
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="ui sidemenu tab" data-tab="products">
            <div class="ui basic segment">
                <h2>Products In Stock</h2>
                <div class="ui divided list modlist" style="text-align:left;">
                    {% for instance in user_viewed_products %}
                    <div class="item">
                      <div class="content">
                        <h4 class="header">{{ instance.product.brand_name }}</h4>
                        <div>Generic name: {{ instance.product.generic_name }}</div>
                        <div>Manufacturer: <strong>{{ instance.product.manufacturer }}</strong></div>
                        <div>Price: {{ instance.price }} PHP&nbsp;&nbsp;|&nbsp;&nbsp;Stock: {{ instance.stock }}</div>
                        {{ instance.product.description }}<br>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="ui sidemenu tab" data-tab="appointments">
        <div class="ui basic segment">
            {% if not current_user.is_admin %}
            <h2>My Appointments</h2>
            <a href="{% url 'appointments:create' slug=object.slug %}">Set an Appointment</a>
            {% if my_appointments_here %}    
            <ul>
                {% for aptmt in my_appointments_here %}
                <li> 
                    <span style="padding-right:15px;">{{ aptmt.date}} ({{ aptmt.timeslot }}): {{ aptmt.service }}</span>
                    <a href="{% url 'appointments:status' appointment_id=aptmt.appointment_id %}?s=Cancelled"><button class="tiny ui orange button">Cancel</button></a>
                </li>
                {% endfor %}
            </ul>
            {% endif %}
            {% endif %}
        </div>

    </div>


    <div class="ui sidemenu {% if current_feedback %}active{% endif %} sidemenu tab" data-tab="feedback">
        <div class="ui basic segment">
            <h4>Average Rating: {{ object.administratordetails.get_average_rating }}</h4>


            <h4>User Feedback</h4>
            <div class="ui segment">
                <div class="ui divided list modlist">
                    {% for f in feedback %}
                    <div class="item">
                        {% if f.user == current_user %}
                        <div class="right floated content">
                            <small>
                                <a href="{% url 'users:detail' slug=object.slug %}?fid={{ f.feedback_id }}">Edit</a> |
                                <a href="{% url 'users:feedback' slug=object.slug %}?fid={{ f.feedback_id }}"><span style="color:#999;">Delete</span></a>
                            </small>
                        </div>
                        {% endif %}
                        <h4 class="ui header">{{ f.user.username }}</h4>
                        <div class="stars stars-{{ f.rating }}"><i class="star icon"></i><i class="star icon"></i><i class="star icon"></i><i class="star icon"></i><i class="star icon"></i></div>
                        <div class="content" style="padding:2px 0;">{{ f.comment }}</div>
                    </div>
                    {% endfor %}
                </div>
            </div>

            {% if not current_user.is_admin %}
                {% if object.is_admin %}
                <form class="ui compact reply form" action="{% url 'users:feedback' slug=object.slug %}" method="POST">
                    {% csrf_token %}

                    {% if current_feedback %}
                    <input type="hidden" name="feedback_id" value="{{ current_feedback.feedback_id }}">
                    {% endif %}

                    <div class="ui form">
                      <div class="inline fields">
                        <label for="rating">Rating:</label>
                        <div class="field">
                            <input type="hidden" id="rating" name="rating" required>
                            <div class="stars stars-input stars-{% if current_feedback %}{{ current_feedback.rating }}{% else %}0{% endif %}" data-input="#rating" data-value="{% if current_feedback %}{{ current_feedback.rating }}{% else %}0{% endif %}">
                                <i class="star icon"></i><i class="star icon"></i><i class="star icon"></i><i class="star icon"></i><i class="star icon"></i>
                            </div>
                        </div>
                        <div class="field">
                            <div id="ratinglabel" name="ratinglabel"></div>
                        </div>
                    </div>
                </div>
                <div class="field">
                  <textarea name="comment" placeholder="Write a feedback for {{ object.username }}">{% if current_feedback %}{{ current_feedback.comment }}{% endif %}</textarea>
              </div>
              <button type="submit" class="ui primary submit labeled icon button">
                  <i class="icon edit"></i> Add Comment
              </button>


          </form>
          {% endif %}
          {% endif %}
        </div>
    </div>


</div>
</div>
</div>
</div>

<script type="text/javascript">

$('.sidemenu .item').on('click', function() {
    $('.sidemenu .item').removeClass('active');
    $(this).addClass('active');
});             

$('.menu .item').tab();
$('.ui.dropdown').dropdown();

function bituin(){
    var stardex = $(this).index();  
    $('.stars-input').each(function(index) {
        $(this)
        .removeClass('stars-0')
        .removeClass('stars-1')
        .removeClass('stars-2')
        .removeClass('stars-3')
        .removeClass('stars-4')

        if(stardex<5) {
            $(this).addClass('stars-'+(stardex+1));
            $($(this).attr('data-input')).val(stardex+1);
            $(this).attr('data-value', stardex+1);
            var rate = $(this).attr('data-value');
            if (rate == "1") $('#ratinglabel').text("Poor");
            else if (rate == "2") $('#ratinglabel').text("Okay");
            else if (rate == "3") $('#ratinglabel').text("Good");
            else if (rate == "4") $('#ratinglabel').text("Satisfactory");
            else if (rate == "5") $('#ratinglabel').text("Excellent");
        } else {
        }
    })


}
$('.stars-input > .star').click(bituin);
$('.stars-input > .star').hover(
    function() {
        var stardex = $(this).index();  
        $('.stars-input').each(function(index) {
            $(this)
            .removeClass('stars-0')
            .removeClass('stars-1')
            .removeClass('stars-2')
            .removeClass('stars-3')
            .removeClass('stars-4')
            .removeClass('stars-5')

            if(stardex<5) {
                $(this).addClass('stars-'+(stardex+1));
            } else {
            }
        })
    },
    function() {
        $parent = $(this).parent();
        $parent
        .removeClass('stars-0')
        .removeClass('stars-1')
        .removeClass('stars-2')
        .removeClass('stars-3')
        .removeClass('stars-4')
        .removeClass('stars-5')

        var val = $parent.attr('data-value');
        if(val < 5) {
            $parent.addClass('stars-'+val);
        } else {
        }
    });
</script>

{% endblock %}