src/appointments/urls.py
from django.conf.urls import url

from appointments.views import (
    AppointmentTemplate, AppointmentCreateDelete, AppointmentStatus
)

urlpatterns = [
    url(r'^create/(?P<slug>[-\w]+)/$', AppointmentTemplate.as_view(), name='create'),
    url(r'^edit/(?P<appointment_id>\d+)/$', AppointmentStatus.as_view(), name='status'),
    url(r'^(?P<slug>[-\w]+)/$', AppointmentCreateDelete.as_view(), name='base'),
]

src/dashboard/urls.py
from django.conf.urls import (url, include)
from django.contrib import admin

from dashboard.views import (
    DashboardHome, InstitutionList, 
    ServiceView, ServiceDeleteView,
    ProductView, ProductDeleteView
)

urlpatterns = [
    url(r'^$', DashboardHome.as_view(), name='home'),
    url(r'^search/', InstitutionList.as_view(), name='institution-list'),
    
    url(r'^services/delete', ServiceDeleteView.as_view(), name='services-delete'),
    url(r'^services/', ServiceView.as_view(), name='services'),

    url(r'^products/delete', ProductDeleteView.as_view(), name='products-delete'),
    url(r'^products/', ProductView.as_view(), name='products')
]

src/medcentermanager/urls.py
from django.conf.urls import (url, include)
from django.contrib import admin

from users.views import (RegistrationView, LoginView, LogoutView)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^appointments/', include('appointments.urls', namespace='appointments')),
    
    url(r'^registration/(?P<user_type>\w+)', RegistrationView.as_view(), name='registration'),
    url(r'^login/', LoginView.as_view(), name='login'),
    url(r'^logout/', LogoutView.as_view(), name='logout')
]

src/users/urls.py
from django.conf.urls import (url, include)

from users.views import (
    UserDetailView, UserUpdateView, FeedbackView
)


urlpatterns = [
    url(r'^edit/$', UserUpdateView.as_view(), name='update'),
    url(r'^(?P<slug>[-\w]+)/feedback/$', FeedbackView.as_view(), name='feedback'),
    url(r'^(?P<slug>[-\w]+)/$', UserDetailView.as_view(), name='detail')
]

src/appointments/models.py
from django.db import models
from django.contrib.auth import get_user_model

from users.models import AdministratorDetails
from dashboard.models import Service

User = get_user_model()


class Timeslot(models.Model):

    timeslot_id = models.AutoField(primary_key=True)
    start_time = models.CharField(max_length=255, null=True)
    end_time = models.CharField(max_length=255, null=True)

    def __str__(self):
        return '{} - {}'.format(self.start_time, self.end_time)


class Appointment(models.Model):

    appointment_id = models.AutoField(primary_key=True)
    timeslot = models.ForeignKey(Timeslot, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    admin = models.ForeignKey(AdministratorDetails, on_delete=models.CASCADE)
    date = models.DateField(auto_now=False, auto_now_add=False)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    status = models.CharField(max_length=255, default='Pending')
    additional_info = models.TextField()

    def __str__(self):
        return '{} for {} at {} from {} on {}'.format(self.service, self.user, self.admin, self.timeslot, self.date)

src/appointments/views.py
from django.shortcuts import (render, redirect)
from django.views.generic import(TemplateView, View)
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.urls import reverse

from users.models import AdministratorDetails
from appointments.models import (
    Timeslot, Appointment
)
from appointments.utils import get_date
from dashboard.models import Service

from datetime import datetime

User = get_user_model()


class AppointmentTemplate(TemplateView):
    template_name = 'appointments/create_appointment.html'

    def get_context_data(self, *args, **kwargs):
        context = super(AppointmentTemplate, self).get_context_data(**kwargs)
        context['current_user'] = self.request.user
        
        slug = self.kwargs.get('slug')
        user_viewed = User.objects.get(slug=slug)
        
        if not user_viewed.is_admin:
            messages.error(request, 'User being viewed is not an institution')
            return redirect(reverse('users:detail', kwargs={'slug': slug}))

        context['user_viewed'] = user_viewed

        d = self.request.GET.get('d')
        
        if d:
            date = get_date(d) 
            context['date'] = date

            taken_appointments = Appointment.objects.filter(admin__user=user_viewed, date=date, status='Accepted')
            taken_appointment_timeslots_ids = [ appointment.timeslot.timeslot_id for appointment in taken_appointments ]
            
            context['available_appointment_timeslots'] = Timeslot.objects.exclude(timeslot_id__in=taken_appointment_timeslots_ids)
            # context['my_appointments_here'] = Appointment.objects.filter(user=self.request.user, admin__user=user_viewed)
        
        return context


class AppointmentCreateDelete(View):

    def get(self, request, *args, **kwargs):
        aptmt_id = request.GET.get('aptmtid')
        slug = kwargs.get('slug')
        aptmt = Appointment.objects.get(appointment_id=aptmt_id)
        admin_user = User.objects.get(slug=slug)

        if aptmt.user == self.request.user and aptmt.admin.user == admin_user:
            aptmt.delete()
            messages.success(request, 'Successfully deleted your appointment')
        else:
            messages.error(request, 'Error in deleting your appointment')
            
        return redirect(reverse('users:detail', kwargs={'slug': slug}))

    def post(self, request, *args, **kwargs):
        try: 
            if self.request.user.is_admin: 
                messages.error(request, 'You are an institution, you cannot make an appointment')
            else:
                date = get_date(request.POST.get('date')) 
                timeslot_id = request.POST.get('timeslot')
                service_name = request.POST.get('service')  
                additional_info = request.POST.get('additional_info')
                slug = kwargs.get('slug')
                
                timeslot = Timeslot.objects.get(timeslot_id=timeslot_id)
                service = Service.objects.get(name=service_name)
                admin_user = User.objects.get(slug=slug)
                admin_instance = AdministratorDetails.objects.get(user=admin_user)

                print(timeslot)
                print(timeslot.start_time, timeslot.end_time)
                print(admin_instance.open_time, admin_instance.close_time)

                tmslt_start_time = datetime.strptime(timeslot.start_time, '%H:%M').time()
                tmslt_end_time = datetime.strptime(timeslot.end_time, '%H:%M').time()
                inst_open_time = datetime.strptime(admin_instance.open_time, '%H:%M').time()
                inst_close_time = datetime.strptime(admin_instance.close_time, '%H:%M').time()
                within_institution_open_and_close = tmslt_start_time >= inst_open_time and tmslt_start_time <= inst_close_time and tmslt_end_time >= inst_open_time and tmslt_end_time <= inst_close_time

                print('timeslot requested: {} - {}'.format(timeslot.start_time, timeslot.end_time))

                print('Timeslot Admin time T/F')
                print('{} >= {}: {}'.format(tmslt_start_time, inst_open_time, tmslt_start_time >= inst_open_time ))
                print('{} <= {}: {}'.format(tmslt_start_time, inst_close_time, tmslt_start_time <= inst_close_time ))
                print('{} >= {}: {}'.format(tmslt_end_time, inst_open_time, tmslt_end_time >= inst_open_time))
                print('{} <=  {}: {}'.format(tmslt_end_time, inst_close_time, tmslt_end_time <= inst_close_time))

                print('-----------')
                print(within_institution_open_and_close)
                print('-----------')

                if within_institution_open_and_close:
                    Appointment.objects.create(
                        date=date,
                        status='Pending',
                        admin=admin_instance,
                        service=service, 
                        timeslot=timeslot,
                        user=self.request.user,
                        additional_info=additional_info
                    )
                    messages.success(request, 'You have successfully requested an appointment on {} from {} for {} at {}'
                                            .format(date, timeslot, service, admin_user.username))
                    return redirect(reverse('users:detail', kwargs={'slug': slug}))    
                else:
                    messages.error(request, "The timeslot you requested is not within this instutition's opening and closing time") 
                    return redirect(reverse('appointments:create', kwargs={'slug': slug}))
        except Exception as e:
            print(e)
            messages.error(request, 'Creating an appointment failed. Please fill out fields correctly')
            return redirect(reverse('appointments:create', kwargs={'slug': slug}))
        
 

class AppointmentStatus(View):

    def get(self, request, *args, **kwargs):
        appointment_id = kwargs.get('appointment_id')
        status = request.GET.get('s')

        appointment = Appointment.objects.get(appointment_id=appointment_id)

        if appointment.admin.user == request.user or appointment.user == request.user:
            appointment.status = status
            appointment.save()

            messages.success(request, "Successfully set appointment on {} at {} to '{}'"
                                        .format(appointment.date, appointment.timeslot, status.upper()))            
        else:
            print('Appointment admin and request.user are not the same')
            messages.error(request, "There was a problem with changing the appointment's status")
        
        return redirect(reverse('dashboard:home'))

src/templates/appointments/create_appointment.html
<div class="ui grid container centered aligned">
    <div class="row">
        <div class="eight wide computer column thirteen wide tablet thirteen wide mobile">       

            {% extends "base.html" %}

            {% block content %}

            <div class="row">
                <div class="ui secondary menu" style="border-bottom: 2px solid rgba(34, 36, 38, 0.15);" >
                  <a class="item" href={% url 'dashboard:home' %}>Home</a>
                  <a class="item" href={% url 'dashboard:institution-list' %}>View institutions</a>
                  <a class="item" href={% url 'users:update' %}>Edit My Profile</a>
                  <div class="right secondary menu">
                    <a class="ui item" href={% url 'logout' %}> <i class="sign out icon"></i> Logout</a>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="ui stacked segment" style="margin-top: 20px">
                {% if not current_user.is_admin %}
                <h1 class="ui header" align="center">Set an Appointment
                <div class="sub header">with <strong>{{ user_viewed.username }}</strong></div></h1>
                <p></p>

                <form class="ui form" action="{% url 'appointments:base' slug=user_viewed.slug %}" method="POST" style="padding:8px 15px;">
                    {% csrf_token %}
                    <div class="two fields">
                        <div class="required field">
                            <label for="date">Date:</label>
                            <div class="ui calendar" id="appointment-calendar">
                                <div class="ui input left icon">
                                    <i class="calendar icon"></i>
                                    <input type="text" name="date" placeholder="Date" {% if date %} value="{{ date }}" {% endif %}>
                                </div>
                            </div>
                        </div>

                        <div class="required field">
                            <label for="timeslot">Timeslot: </label>
                            <select name="timeslot" id="">
                                <option value="none">--- Select ---</option>
                                {% for aptmt in available_appointment_timeslots %}
                                <option value="{{ aptmt.timeslot_id }}">{{ aptmt }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="required field">
                        <label for="service">Service: </label>
                        <select class="ui dropdown" name="service">
                            <option value="">Select service...</option>
                            {% for service in user_viewed.administratordetails.services.all %}
                            <option value="{{ service.name }}">{{ service.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    
                    <div class="required field">
                        <label for="">Additional Comments:</label>
                        <textarea name="additional_info" id="" cols="30" rows="5" placeholder="Any requests, info, questions, etc."></textarea>
                    </div>
                    <p>&nbsp;</p>
                    <div style="text-align:center;">
                        <input class="ui positive button" type="submit" value="Submit" />
                        <a class="ui button" href={% url 'dashboard:home' %}>Cancel</a>
                    </div>                
                </form>
                <br>
                {% endif %}
            </div>
        </div>

        </div>
    </div>
</div>

<script type="text/javascript">
    $('.ui.dropdown').dropdown();
</script>

{% endblock %}